import Config

# Configure your database
database_url = System.get_env("DATABASE_URL")

username = System.get_env("DB_USERNAME", "postgres")
password = System.get_env("DB_PASSWORD", "postgres")
hostname = System.get_env("DB_HOST", "localhost")
port = String.to_integer(System.get_env("DB_PORT") || "6432")
database = System.get_env("DB_NAME", "fastcheck_prod")

database_pooling_mode =
  case System.get_env("DATABASE_POOLING_MODE") do
    nil ->
      if is_nil(database_url) and port == 6432 do
        :pgbouncer_transaction
      else
        :direct
      end

    value ->
      case String.trim(value) |> String.downcase() do
        "pgbouncer_transaction" -> :pgbouncer_transaction
        "pgbouncer_session" -> :pgbouncer_session
        _ -> :direct
      end
  end

database_prepare_mode =
  case System.get_env("DB_PREPARE_MODE") do
    nil ->
      case database_pooling_mode do
        :pgbouncer_transaction -> :unnamed
        _ -> :named
      end

    value ->
      case String.trim(value) |> String.downcase() do
        "unnamed" -> :unnamed
        _ -> :named
      end
  end

oban_notifier_name =
  case System.get_env("OBAN_NOTIFIER") do
    nil ->
      case database_pooling_mode do
        :pgbouncer_transaction -> :pg
        _ -> :postgres
      end

    value ->
      case String.trim(value) |> String.downcase() do
        "pg" -> :pg
        _ -> :postgres
      end
  end

oban_notifier =
  case oban_notifier_name do
    :pg -> {Oban.Notifiers.PG, []}
    :postgres -> {Oban.Notifiers.Postgres, []}
  end

repo_connection_opts =
  if database_url do
    [url: database_url]
  else
    [
      username: username,
      password: password,
      hostname: hostname,
      port: port,
      database: database
    ]
  end

config :fastcheck,
       FastCheck.Repo,
       repo_connection_opts
       |> Keyword.merge(
         prepare: database_prepare_mode,
         stacktrace: true,
         show_sensitive_data_on_connection_error: true,
         pool_size: 20,
         queue_target: 50,
         queue_interval: 1_000,
         preallocate: true,
         # Query timeout: 30 seconds for all queries
         timeout: 30_000,
         # Log all queries with timing in development
         log: :info
       )

config :fastcheck, :database_pooling,
  mode: database_pooling_mode,
  prepare: database_prepare_mode

config :fastcheck, :oban_runtime, notifier: oban_notifier_name
config :fastcheck, Oban, notifier: oban_notifier

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fastcheck, FastCheckWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  cors_origins: [System.get_env("DEV_CORS_ORIGIN", "*")],
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bwacjdLNrUIRXobPOlKcOVcenk24MXSG3lgvALulPJOYKIDUIOzGw75pMy4V2P+3",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fastcheck, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fastcheck, ~w(--watch)]}
  ]

config :fastcheck, :enable_metrics, true

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
live_reload_pattern_sources = [
  "priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
  "priv/gettext/.*(po)$",
  "lib/fastcheck_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
]

config :fastcheck, FastCheckWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    pattern_sources: live_reload_pattern_sources
  ]

# Enable dev routes for dashboard and mailbox
config :fastcheck, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
