defmodule FastCheckWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fastcheck

  @endpoint_config Application.compile_env(:fastcheck, __MODULE__, [])

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_overrides @endpoint_config |> Keyword.get(:session_options, [])

  @live_reload_options compile_live_reload_options(@endpoint_config)

  @session_options [
                     store: :cookie,
                     key: "_fastcheck_key",
                     signing_salt: "TZ10yE5o",
                     same_site: "Lax"
                   ]
                   |> Keyword.merge(@session_overrides)

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fastcheck,
    gzip: not code_reloading?,
    only: FastCheckWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader, @live_reload_options
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fastcheck
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FastCheckWeb.Router

  defp compile_live_reload_options(config) do
    config
    |> Keyword.get(:live_reload)
    |> case do
      nil -> []
      live_reload ->
        {pattern_sources, live_reload} = Keyword.pop(live_reload, :pattern_sources, [])

        patterns =
          pattern_sources
          |> Enum.reject(&is_nil/1)
          |> Enum.map(&Regex.compile!(&1))

        maybe_put_patterns(live_reload, patterns)
    end
  end

  defp maybe_put_patterns(opts, []), do: opts
  defp maybe_put_patterns(opts, patterns), do: Keyword.put(opts, :patterns, patterns)
end
