defmodule FastCheckWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fastcheck

  # @endpoint_config removed to prevent compile-time config freezing

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fastcheck_key",
    signing_salt: "TZ10yE5o",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fastcheck,
    gzip: not code_reloading?,
    only: FastCheckWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fastcheck

    # Process live_reload options at compile-time for dev only
    # We use get_env here because we are in the macro expansion phase
    # and this block only exists in dev.
    @live_reload_opts_raw Application.get_env(:fastcheck, __MODULE__, [])
                          |> Keyword.get(:live_reload, [])

    @live_reload_patterns (
                            {pattern_sources, opts} =
                              Keyword.pop(@live_reload_opts_raw, :pattern_sources, [])

                            patterns = Enum.map(pattern_sources, &Regex.compile!/1)

                            if patterns == [],
                              do: opts,
                              else: Keyword.put(opts, :patterns, patterns)
                          )

    plug Phoenix.LiveReloader, @live_reload_patterns
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug FastCheckWeb.Plugs.SecurityHeaders

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Runtime CORS configuration
  def cors_origins do
    Application.get_env(:fastcheck, __MODULE__, [])
    |> Keyword.get(:cors_origins, ["https://example.com"])
    |> case do
      nil -> ["https://example.com"]
      origins when is_list(origins) -> origins
      origin -> [origin]
    end
  end

  plug CORSPlug, origin: &__MODULE__.cors_origins/0

  plug FastCheckWeb.Router
end
